// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SET11105_CW2.Data;

namespace SET11105_CW2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220418091955_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SET11105_CW2.Models.Cause", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasMaxLength(10000);

                    b.Property<int>("numOfSignatures")
                        .HasColumnType("int");

                    b.Property<string>("subjetc")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("timeOfPublish")
                        .HasColumnType("datetime");

                    b.HasKey("ID");

                    b.ToTable("cause");
                });

            modelBuilder.Entity("SET11105_CW2.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("password")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("username")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.ToTable("member");
                });
#pragma warning restore 612, 618
        }
    }
}
